[project]
name = "bird"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "backoff>=2.2.1",
    "func-timeout>=4.3.5",
    "openai>=1.99.5",
    "pandas>=2.3.1",
    "sqlparse>=0.5.3",
]
